# Generated by Django 6.0.3 on 2026-04-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.PositiveBigIntegerField()),
                ('area', models.PositiveIntegerField(help_text='Area in square kilometers')),
                ('region', models.CharField(choices=[('Europe', 'Europe'), ('Asia', 'Asia'), ('Africa', 'Africa'), ('North America', 'North America'), ('South America', 'South America'), ('Oceania', 'Oceania')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('neighbors', models.ManyToManyField(blank=True, to='countries.country')),
                ('organizations', models.ManyToManyField(blank=True, related_name='countries', to='countries.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='countries.country')),
            ],
            options={
                'ordering': ['-population', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speakers_percent', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='countries.country')),
            ],
            options={
                'ordering': ['-speakers_percent', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
