# Generated by Django 6.0.3 on 2026-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
